[managers.paru]
items = [
  "mg",
  "zsh",
  "stow",
  "eza",
  "wl-clipboard",
  "trash-cli",
  "ufw",
  "opensnitch",
  "ansible",
  "mpv",
  "emacs-wayland",
  "signal-desktop",
  "gimp",
  # AUR
  "patool",
  "librewolf-bin",
  "xdg-ninja",
]

[managers.systemctl_user]
items = [
  "emacs.service",
]
