imports = [
    "DE",
    "arch",
    "audio",
    "btrfs",
    "core",
    "essential_software",
    "laptop",
    "misc_software",
    "radeon",
]

[managers.paru]
items = [
  "rclone",
  "usbgaurd",
  "waydroid",
]
