format = """
$directory\
$cmd_duration\
$line_break\
$character
"""

[directory]
style = "bright white"

[cmd_duration]
format = "[$duration]($style)"
style = "dimmed white"

[character]
success_symbol = "[>](bright white)"
error_symbol = "[x](bright white)"
