[managers.paru]
items = [
  "btrfs-progs",
  "snapper",
  # AUR
  "snap-pac",
  "snapper-rollback",
]

[managers.systemctl_enable]
items = [
  "btrfs-scrub@btrfsroot.timer",
  "btrfs-scrub@-.timer",
  "btrfs-scrub@\x2esnapshots.timer",
  "btrfs-scrub@home.timer",
  "btrfs-scrub@root.timer",
  "btrfs-scrub@var.timer",
  "btrfs-scrub@games.timer",
]
