[managers.system]
items = [
  "rebos",
  "linux-zen",
  "linux-zen-headers",
  "linux-firmware",
  "base",
  "base-devel",
  "sudo",
  "btrfs-progs",
  "dash",
  "flatpak",
  "amd-ucode",
  "networkmanager",
  "systemd-resolvconf",
  "snapper",
  "chrony",
  "neovim",
  "zsh",
  # AUR
  "paru",
  "dashbinsh",
]

[managers.flatpak]
items = [
  "com.github.tchx84.Flatseal",
]
