[managers.paru]
items = [
  "rebos",
  "linux-zen",
  "linux-zen-headers",
  "linux-firmware",
  "base",
  "base-devel",
  "sudo",
  "btrfs-progs",
  "e2fsprogs",
  "dash",
  "shellcheck",
  "flatpak",
  "amd-ucode",
  "networkmanager",
  "systemd-resolvconf",
  "xdg-user-dirs",
  "noto-fonts",
  "ttf-liberation",
  "ttf-firacode-nerd",
  # AUR
  "paru",
  "dashbinsh",
]

[managers.flatpak]
items = [
  "com.github.tchx84.Flatseal",
]

[managers.systemctl_now]
items = [
  "NetworkManager.service",
  "systemd-resolved.service",
]

[managers.systemctl_enable]
items = [
  "systemd-boot-update.service",
]

[managers.usermod]
items = [
  "wheel",
  "storage",
]
