[managers.system]
items = [
  "rebos",
  "linux-zen",
  "linux-zen-headers",
  "linux-firmware",
  "base",
  "base-devel",
  "sudo",
  "btrfs-progs",
  "e2fsprogs",
  "dash",
  "flatpak",
  "amd-ucode",
  "networkmanager",
  "systemd-resolvconf",
  "neovim",
  "zsh",
  "ufw",
  # AUR
  "paru",
  "dashbinsh",
]

[managers.flatpak]
items = [
  "com.github.tchx84.Flatseal",
]

[managers.serv-now]
items = [
  "NetworkManager.service",
  "systemd-resolved.service",
]

[managers.serv-enable]
items = [
  "systemd-boot-update.service",
]
