[managers.system]
items = [
  "neovim",
  "zsh",
  "eza",
  "ufw",
  "opensnitch",
  "ansible",
  "mpv",
  "emacs-wayland",
  "signal-desktop",
  # AUR
  "patool",
  "librewolf-bin",
  "xdg-ninja",
]
