[managers.system]
items = [
  "emacs-wayland",
  "gimp",
  "signal-desktop",
  # AUR
  "librewolf-bin",
  "anki-bin",
]

[managers.flatpak]
items = [
  "com.belmoussaoui.Authenticator",
  "com.stremio.Stremio",
]
