[managers.system]
items = [
  "mpv",
  "eza",
  "emacs-wayland",
  "gimp",
  "signal-desktop",
  # AUR
  "librewolf-bin",
  "anki-bin",
  "hakuneko-desktop-nightly",
  "kcc",
  "xdg-ninja",
]

[managers.flatpak]
items = [
  "com.belmoussaoui.Authenticator",
  "com.stremio.Stremio",
  "io.gitlab.idevecore.Pomodoro",
  "io.freetubeapp.FreeTube",
]
