[managers.paru]
items = [
  "gimp",
]

[managers.flatpak]
items = [
  "com.belmoussaoui.Authenticator",
  "com.stremio.Stremio",
  "io.gitlab.idevecore.Pomodoro",
  "io.freetubeapp.FreeTube",
  "io.github.hakuneko.HakuNeko",
  "io.github.ciromattia.kcc",
  "net.ankiweb.Anki",
]
