[managers.system]
items = [
  "gimp",
  # AUR
  "anki-bin",
  "hakuneko-desktop-nightly",
  "kcc",
]

[managers.flatpak]
items = [
  "com.belmoussaoui.Authenticator",
  "com.stremio.Stremio",
  "io.gitlab.idevecore.Pomodoro",
  "io.freetubeapp.FreeTube",
]
