[managers.system]
items = [
  "mesa",
  "vulkan-radeon",
  "libva-mesa-driver",
  "mesa-vdpau",
  # 32-bit
  "lib32-mesa",
  "lib32-vulkan-radeon",
  "lib32-libva-mesa-driver",
  "lib32-mesa-vdpau",
]
